create table if not exists sellers(
  id varchar(100) not null,
  pubkeyhash varchar(200) default null,
  address varchar(200) default null,
  username varchar(50) not null,
  email varchar(100) not null,
  password_hash varchar(255) not null,
  verified boolean default false,
  country varchar(10) not null,
  completed_sales int unsigned default 0,
  response_time bigint unsigned default 0,
  acceptance_time bigint unsigned default 0,
  trade_terms varchar(1000) default null,
  terms_accepted boolean not null,
  avatar_base varchar(255) not null,
  avatar_path varchar(255) not null,
  public_ip varchar(100) not null,
  created_at timestamp default current_timestamp,
  schema_v int unsigned not null,
  primary key(id),
  unique(email),
  unique(pubkeyhash),
  unique(username)
) ENGINE=InnoDB;
