create table if not exists products(
  id varchar(50) not null,
  state varchar(100) default "created",
  state_label varchar(500) default "",
  moderated boolean default false,
  seller_id varchar(20) not null,
  name varchar(200) not null,
  price int unsigned not null,
  sku varchar(100) not null,
  model varchar(200) not null,
  brand varchar(200) not null,
  features mediumtext not null,
  category varchar(100) not null,
  keywords varchar(100) not null,
  bullet_list text not null,
  paused boolean not null,                     
  color varchar(100) not null,
  color_name varchar(100) not null,
  variations varchar(1000) not null,
  quality varchar(50) not null,
  country varchar(10) not null,
  media_url varchar(500) not null,
  image_path varchar(500) not null,
  video_path varchar(500) not null,
  image_set varchar(500) not null,
  video_set varchar(500) not null,
  discount boolean not null,
  discount_value int unsigned not null,
  shipping_weight decimal(10, 3) not null,
  shipping_length decimal(10, 2) not null,
  shipping_width decimal(10, 2) not null,
  shipping_height decimal(10, 2) not null,
  shipping_city varchar(255) not null,
  shipping_postal varchar(50) not null,
  shipping_instructions varchar(1000) not null,
  shipping_fragile boolean not null,
  updated_at timestamp default current_timestamp,      
  created_at timestamp default current_timestamp,        
  schema_v int unsigned not null,
  primary key(id),
  unique(sku),
  index idx_created_at (created_at),
  index idx_seller_id (seller_id)
) ENGINE=InnoDB;


