create table if not exists orders(
  id varchar(100) not null,
  finished boolean default false,
  scanning boolean default false,
  status_log varchar(100) default "created",
  seller_id varchar(20) not null,
  buyer_pubkeyhash varchar(100) not null,
  seller_pubkeyhash varchar(100) not null,  
  ada_price decimal(10, 2) not null,
  contract_address varchar(100) not null,
  contract_state int default 0,
  contract_price int unsigned not null,
  contract_collateral int unsigned not null,
  contract_units int unsigned not null,
  product_id varchar(20) not null,
  product_sku varchar(100) not null,
  product_price int unsigned not null,
  product_collateral int unsigned not null,
  product_discount boolean not null,
  product_discount_value int unsigned not null,
  watch_until bigint not null,
  pending_until bigint not null,
  pending_tx varchar(200) default null,
  pending_block varchar(200) default null,
  pending_datum_hash varchar(200) default null,
  pending_inline_datum varchar(200) default null,
  pending_redeemer varchar(200) default null,
  created_at timestamp default current_timestamp,
  schema_v int unsigned default 0,
  primary key(id),
  index idx_scanning (id,finished,scanning)
) ENGINE=InnoDB;
