apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  user: marketplace
  master: mysql
  slave: mysql
  port: "3306"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-config
data:
  redis: redis://redis-streaming-srv:6379

