apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  master: mongodb+srv://doadmin:d5ft714ls90K2TB8@testing-18bbc3f1.mongo.ondigitalocean.com/admin?tls=true&authSource=admin
  slave: mongodb+srv://doadmin:d5ft714ls90K2TB8@testing-18bbc3f1.mongo.ondigitalocean.com/admin?tls=true&authSource=admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-config
data:
  redis: redis://redis-streaming-srv:6379

