create table if not exists orders(
  id varchar(100) not null,
  finished boolean default false,
  completed boolean default false,
  scanned_at bigint default 0,
  country varchar(20) not null,
  status_log varchar(100) default "created",
  seller_id varchar(100) not null,
  buyer_pubkeyhash varchar(100) not null,
  seller_pubkeyhash varchar(100) not null,  
  buyer_address varchar(200) not null,
  seller_address varchar(200) not null,
  buyer_username varchar(100) not null,  
  ada_price decimal(10, 2) not null,
  contract_address varchar(100) not null,
  contract_params text not null,
  contract_state int default null,
  contract_price int unsigned not null,
  contract_fee int unsigned not null,
  contract_units int unsigned not null,
  product_id varchar(20) not null,
  product_name varchar(200) not null,
  product_price int unsigned not null,
  product_sku varchar(100) not null,
  product_model varchar(200) not null,
  product_brand varchar(200) not null,
  product_features mediumtext not null,
  product_bullet_list text not null,
  product_discount boolean not null,
  product_discount_value int unsigned not null,
  product_media_url varchar(500) not null,
  product_image_path varchar(500) not null,
  product_video_path varchar(500) not null,
  product_image_set varchar(500) not null,
  product_video_set varchar(500) not null,
  watch_until bigint not null,
  pending_until bigint not null,
  shipping_until bigint not null,
  expire_until bigint not null,
  pending_tx varchar(200) default null,
  pending_block varchar(200) default null,
  pending_metadata text default null,
  returned_tx varchar(200) default null,
  returned_block varchar(200) default null,
  locking_tx varchar(200) default null,
  locking_block varchar(200) default null,
  canceled_tx varchar(200) default null,
  canceled_block varchar(200) default null,
  shipping_tx varchar(200) default null,
  shipping_block varchar(200) default null,
  shipping_metadata text default null,
  appealed_tx varchar(200) default null,
  appealed_block varchar(200) default null,  
  received_tx varchar(200) default null,
  received_block varchar(200) default null,
  collected_tx varchar(200) default null,
  collected_block varchar(200) default null,  
  updated_at timestamp default current_timestamp,
  created_at timestamp default current_timestamp,
  schema_v int unsigned default 0,
  primary key(id),
  index idx_finished (finished),
  index idx_completed (completed),
  index idx_created_at (created_at),
  index idx_scanned_at (scanned_at),
  index idx_seller (seller_id),
  index idx_buyer (buyer_pubkeyhash),
  FOREIGN KEY (seller_id) REFERENCES sellers(id)
) ENGINE=InnoDB;
