{
 "title": "Kubernetes - Deployment - 2024",
 "description": "Kubernetes Deployment from Quarks",
 "tags": [
  "kubernetes",
  "deployment",
  "KubePodNotReady",
  "KubePodCrashLooping",
  "KubeContainerOOMKilled",
  "KubeHpaReplicasMismatch",
  "KubeletPodStartUpLatencyHigh",
  "KubeDeploymentGenerationMismatch",
  "KubeDeploymentReplicasMismatch"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation, prometheus)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation{prometheus=\"$environment\"},namespace)"
    }
   },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation{namespace=\"$namespace\", prometheus=\"$environment\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Replicas ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(kube_deployment_status_replicas_available{deployment=\"$deployment\",prometheus=\"$environment\",namespace=\"$namespace\"}) without (instance, pod)",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Desired replicas ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"$deployment\",prometheus=\"$environment\",namespace=\"$namespace\"} * 100 / kube_deployment_status_replicas{deployment=\"$deployment\",prometheus=\"$environment\",namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "min(sum_over_time(kube_deployment_status_replicas_available{deployment=\"$deployment\",prometheus=\"$environment\",namespace=\"$namespace\"} [$__interval])) without (instance, pod)",
     "legendFormat": "Available"
    },
    {
     "expr": "min(sum_over_time(kube_deployment_status_replicas{deployment=\"$deployment\",prometheus=\"$environment\",namespace=\"$namespace\"} [$__interval])) without (instance, pod)",
     "legendFormat": "Desired"
    },
    {
     "expr": "min(sum_over_time(kube_deployment_status_replicas_unavailable{deployment=\"$deployment\",prometheus=\"$environment\",namespace=\"$namespace\"} [$__interval])) without (instance, pod)",
     "legendFormat": "Unavailable"
    }
   ]
  },
  {
   "title": "CPU Usage ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",prometheus=\"$environment\",pod=~\"$deployment-.*\"}[2m])) * 100 / sum(kube_pod_container_resource_limits{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\", resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",prometheus=\"$environment\",pod=~\"$deployment-.*\"}) * 100 / sum(kube_pod_container_resource_limits{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\", unit=\"byte\"}) "
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",prometheus=\"$environment\",pod=~\"$deployment-.*\"}[2m]))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\", resource=\"cpu\", unit=\"core\"}) ",
     "legendFormat": "CPU limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\", resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "CPU requests"
    }
   ]
  },
  {
   "title": "Memory usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",prometheus=\"$environment\",pod=~\"$deployment-.*\"}) ",
     "legendFormat": "Memory usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\", unit=\"byte\"}) ",
     "legendFormat": "Memory limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\", unit=\"byte\"}) ",
     "legendFormat": "Memory requests"
    }
   ]
  },
  {
   "title": "Network I/O  ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",prometheus=\"$environment\",pod=~\"$deployment-.*\"}[5m]))",
     "legendFormat": "Out"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",prometheus=\"$environment\",pod=~\"$deployment-.*\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Deployment \"$deployment\" - detailed ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "CPU Usage (request/limit) by POD",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\",  container!=\"\"}[1m])) by (pod)",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\", resource=\"cpu\", unit=\"core\", container!=\"\"}) by (pod)",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\", resource=\"cpu\", unit=\"core\", container!=\"POD\", container!=\"\"}) by (pod)",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Usage by POD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",prometheus=\"$environment\",pod=~\"$deployment-.*\"}[2m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Mem Usage (request/limit) by POD",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\"}) by (pod)>0",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\", unit=\"byte\"}) by (pod)>0",
     "legendFormat": "Request"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\", unit=\"byte\"}) by (pod)>0",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Memory Usage by POD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"$namespace\",prometheus=\"$environment\",pod=~\"$deployment-.*\"})",
     "legendFormat": "{{ pod }} "
    }
   ]
  },
  {
   "title": "Current Network Usage by POD",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{prometheus=\"$environment\", namespace=~\"$namespace\",pod=~\"$deployment-.*\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{prometheus=\"$environment\", namespace=~\"$namespace\",pod=~\"$deployment-.*\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_total{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\"}[5m])) by (pod)"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{prometheus=\"$environment\", namespace=~\"$namespace\", pod=~\"$deployment-.*\"}[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "Network I/O by POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_bytes_total{namespace=\"$namespace\",prometheus=\"$environment\",pod=~\"$deployment-.*\"}[5m]))",
     "legendFormat": "{{pod}} <- in"
    },
    {
     "expr": "-sum (rate(container_network_transmit_bytes_total{namespace=\"$namespace\",prometheus=\"$environment\",pod=~\"$deployment-.*\"}[5m])) by (pod)",
     "legendFormat": "{{pod}} -> out"
    }
   ]
  }
 ]
}