apiVersion: v1
kind: Service
metadata:
  name: blockchain-api
spec:
  type: NodePort
  selector:
    app: blockchain-api
    role: blockchain-api
    name: blockchain-api
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080

