apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-main
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend-main
  template:
    metadata:
      labels:
        role: frontend-main
    spec:
      containers:
        - name: frontend-main
          image: pairfy/frontend-main
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"               
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-main
spec:
  selector:
    role: frontend-main
  ports:
    - name: frontend-main
      protocol: TCP
      port: 8000
      targetPort: 80
