apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      role: healthcheck
  template:
    metadata:
      labels:
        role: healthcheck
    spec:
      containers:
        - name: healthcheck
          image: pairfy/healthcheck
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                                                                  
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: healthcheck
spec:
  selector:
    role: healthcheck
  ports:
    - name: healthcheck
      protocol: TCP
      port: 3000
      targetPort: 3000
