apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-gateway
  template:
    metadata:
      labels:
        role: service-gateway
    spec:
      containers:
        - name: service-gateway
          image: pairfy/service-gateway
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-token-secret
                  key: AGENT_TOKEN_KEY
            - name: POD_TIMEOUT
              value: "120000"
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "30000"
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: DATABASE_NAME
              value: service_gateway
            - name: DATABASE_USER
              value: marketplace
            - name: REDIS_HOST
              value: redis://service-state-redis:6379
            - name: PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: blockfrost-key
                  key: key
            - name: KUPO_KEY
              valueFrom:
                secretKeyRef:
                  name: kupo-key
                  key: key
            - name: OGMIOS_KEY
              valueFrom:
                secretKeyRef:
                  name: ogmios-key
                  key: key
            - name: TX_VALID_TIME
              value: "360000"
            - name: TX_WATCH_WINDOW
              value: "960000"
            - name: PENDING_RANGE
              value: "3600000"
            - name: SHIPPING_RANGE
              value: "86400000"
            - name: APPEAL_RANGE
              value: "604800000"
            - name: DELIVERY_RANGE
              value: "864000000"              
            - name: EXPIRING_RANGE
              value: "5184000000"
            - name: NETWORK_ENV
              value: "Preprod"
            - name: FEE_PERCENT
              value: "10"                      
            - name: RSA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: metadata-secret
                  key: private
            - name: RSA_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: metadata-secret
                  key: public
            - name: RSA_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: metadata-secret
                  key: rsa
            - name: AES_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: metadata-secret
                  key: aes
            - name: ELASTIC_NODE
              valueFrom:
                secretKeyRef:
                  name: elastic-endpoint
                  key: key
            - name: ELASTIC_KEY
              valueFrom:
                secretKeyRef:
                  name: elastic-api-key
                  key: key                   
            - name: CORS_DOMAINS
              value: "http://localhost:5173,http://localhost:5174,http://localhost:8080,http://localhost:8081,http://localhost:443,localhost,https://pairfy.dev,https://dashboard.pairfy.dev"
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-gateway
spec:
  selector:
    role: service-gateway
  ports:
    - name: service-gateway
      protocol: TCP
      port: 4000
      targetPort: 4000
