apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-query
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-query
  template:
    metadata:
      labels:
        role: service-query
    spec:
      containers:
        - name: service-query
          image: pairfy/service-query
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                                             
            - name: POD_TIMEOUT
              value: '120000'   
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "120000"
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password  
            - name: ELASTIC_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: elastic-endpoint
                  key: key    
            - name: ELASTIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: elastic-api-key
                  key: key                                    
            - name: DATABASE_NAME
              value: service_query       
            - name: DATABASE_USER
              value: marketplace    
            - name: REDIS_HOST
              value: redis://service-state-redis:6379                                                                                                                                                                                                  
            - name: CORS_DOMAINS
              value: "http://localhost:5173,http://localhost:5174,http://localhost:8080,http://localhost:8081,http://localhost:443,localhost,https://pairfy.dev,https://dashboard.pairfy.dev"                          
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-query
spec:
  selector:
    role: service-query
  ports:
    - name: service-query
      protocol: TCP
      port: 4000
      targetPort: 4000
