apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-chat
  template:
    metadata:
      labels:
        role: service-chat
    spec:
      containers:
        - name: service-chat
          image: pairfy/service-chat
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-token-secret
                  key: AGENT_TOKEN_KEY
            - name: POD_TIMEOUT
              value: "120000"
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "30000"
            - name: REDIS_HOST
              value: redis://service-state-redis:6379
            - name: CORS_DOMAINS
              value: "http://localhost:5173,http://localhost:5174,http://localhost:8080,http://localhost:8081,http://localhost:443,localhost,https://pairfy.dev,https://dashboard.pairfy.dev"
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-chat
spec:
  selector:
    role: service-chat
  ports:
    - name: service-chat
      protocol: TCP
      port: 4000
      targetPort: 4000
