apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-session-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-session-redis
  template:
    metadata:
      labels:
        app: service-session-redis
    spec:
      containers:
        - name: service-session-redis
          image: redis
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: service-session-redis
spec:
  selector:
    app: service-session-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379