apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-gateway-publisher
  template:
    metadata:
      labels:
        role: service-gateway-publisher
    spec:
      containers:
        - name: service-gateway-publisher
          image: pairfy/base-publisher
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                                             
            - name: POD_TIMEOUT
              value: '120000'   
            - name: DATABASE_USER
              value: marketplace
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: service_gateway                                                                                                                                                               
            - name: STREAM_NAME
              value: gateway
            - name: STREAM_SUBJECT
              value: gateway.*              
            - name: QUERY_INTERVAL
              value: "30000"    
            - name: QUERY_LIMIT
              value: "500"                                   
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
