apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-matrix
  template:
    metadata:
      labels:
        role: service-matrix
    spec:
      containers:
        - name: service-matrix
          image: pairfy/service-matrix
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                                              
            - name: POD_TIMEOUT
              value: '120000'   
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "120000"          
            - name: MATRIX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: matrix-api-key
                  key: key                                                                                                                                                                                          
            - name: CORS_DOMAINS
              value: "http://localhost:5173,http://localhost:5174,http://localhost:8080,http://localhost:8081,http://localhost:443,localhost,https://pairfy.dev,https://dashboard.pairfy.dev"                          
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-matrix
spec:
  selector:
    role: service-matrix
  ports:
    - name: service-matrix
      protocol: TCP
      port: 8000
      targetPort: 8000
