apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-seller
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-seller
  template:
    metadata:
      labels:
        role: service-seller
    spec:
      containers:
        - name: service-seller
          image: pairfy/service-seller
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                       
            - name: AGENT_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-token-secret
                  key: AGENT_TOKEN_KEY                       
            - name: POD_TIMEOUT
              value: '120000'   
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "120000"                                                                  
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password   
            - name: DATABASE_NAME
              value: service_gateway       
            - name: DATABASE_USER
              value: marketplace 
            - name: TOKEN_EXPIRATION
              value: "7d"
            - name: CORS_DOMAINS
              value: "http://localhost:5173,http://localhost:8080,http://localhost:8081,http://localhost:443,localhost,https://pairfy.dev,https://dashboard.pairfy.dev"                           
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-seller
spec:
  selector:
    role: service-seller
  ports:
    - name: service-seller
      protocol: TCP
      port: 8000
      targetPort: 8000
