apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-notification
  template:
    metadata:
      labels:
        role: service-notification
    spec:
      containers:
        - name: service-notification
          image: pairfy/service-notification
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                       
            - name: AGENT_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: agent-token-secret
                  key: AGENT_TOKEN_KEY                                       
            - name: POD_TIMEOUT
              value: '120000'   
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "30000"                                                                  
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password   
            - name: DATABASE_NAME
              value: service_notification       
            - name: DATABASE_USER
              value: marketplace 
            - name: REDIS_HOST
              value: redis://service-state-redis:6379  
            - name: MAIL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: blockfrost-key
                  key: key      
            - name: TELEGRAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: blockfrost-key
                  key: key                                          
            - name: CORS_DOMAINS
              value: "http://localhost:5173,http://localhost:5174,http://localhost:8080,http://localhost:8081,http://localhost:443,localhost,https://pairfy.dev,https://dashboard.pairfy.dev"                          
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-notification
spec:
  selector:
    role: service-notification
  ports:
    - name: service-notification
      protocol: TCP
      port: 4000
      targetPort: 4000
