name: healthcheck

on:
  push:
    branches:
      - main
    paths:
      - 'healthcheck/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 19
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}    
      - run: cd healthcheck && docker build -t pairfy/healthcheck .    
      - run: docker push pairfy/healthcheck
      - uses: digitalocean/action-doctl@v2.3.0
        with:
          token: ${{ secrets.OCEAN_API_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8pairfy
      - run: kubectl rollout restart deployment healthcheck

